### ISSUE TITLE
(error) CLUSTERDOWN Hash slot not served

### ISSUE THREAD

**Issue by bartoszx** [jamespedwards42/jamespedwards42.github.io#1]
Hi James
I've been trying to setup cluster with your code since couple of days.
I am starting 3 nodes cluster with mode=global

```
./createMasters.sh 6379 3 redis-cluster-m- jamespedwards42/alpine-redis:3.2
1h2i63hvtun3aobsd4tn6g547
5ltkhbpvqtxxsozj4pq1ivcit
ds4pymh6eqrx0z4fbjqrwtv66

./meetNodes.sh 6379 3 redis-cluster-m-
CLUSTER MEET 10.0.0.2 6379
OK
CLUSTER MEET 10.0.0.5 6381
OK
bd2ab830afb7f7e03f68fa5dcc9f06a51b6781ee 10.0.0.5:6381 master - 0 1476009176788 0 connected
7fa44476f0485179b157ac194dc387490885ab70 10.0.0.2:6379 master - 0 1476009176788 0 connected
c9a871a05bd3529a965f24f884480c932b8a1b6a :6380 myself,master - 0 0 0 connected

./assignSlots.sh 6379 3 redis-cluster-m-
CLUSTER ADDSLOTS 0 - 5461
OK
CLUSTER ADDSLOTS 5462 - 10923
OK
CLUSTER ADDSLOTS 10924 - 16383
OK
```

For now it looks ok but lets try add some keys in Cli mode

```
# redis-cli -h redis-cluster-m-6379
redis-cluster-m-6379:6379> keys *
(empty list or set)
redis-cluster-m-6379:6379> SET mykey "Hello"
(error) MOVED 14687 10.0.0.7:6381
redis-cluster-m-6379:6379> SET mykey "Hello"
(error) MOVED 14687 10.0.0.7:6381
redis-cluster-m-6379:6379> connect redis-cluster-m-6380 6380
redis-cluster-m-6380:6380> SET mykey "Hello"
(error) MOVED 14687 10.0.0.7:6381
redis-cluster-m-6380:6380> connect redis-cluster-m-6381 6381
redis-cluster-m-6381:6381> SET mykey "Hello"
OK
redis-cluster-m-6381:6381> GET mykey
"Hello"
redis-cluster-m-6381:6381> connect redis-cluster-m-6380 6380
redis-cluster-m-6380:6380> GET mykey
(error) MOVED 14687 10.0.0.7:6381
redis-cluster-m-6380:6380> connect redis-cluster-m-6379 6379
redis-cluster-m-6379:6379> GET mykey
(error) MOVED 14687 10.0.0.7:6381
redis-cluster-m-6379:6379> keys *
(empty list or set)
redis-cluster-m-6379:6379>
```

Sometime I see (error) CLUSTERDOWN Hash slot not served

Any idea what I am doing wrong?

**Comment by jamespedwards42** [comment]
I haven't touched this in a while; I might need to do a run through with the latest swarm version.

The MOVED errors occur when you send a Key based command to a node that is not responsible for the corresponding hash slot.  The error tells you which node to connect to instead.  Actual Redis Cluster clients will manage these mappings and connections for you.

Can you send me the steps to re-create the CLUSTERDOWN errors?... I remember getting that sometimes when setting up a new Redis Cluster with Swarm, considering it was transient and standing up a cluster is a one time kind of thing I didn't worry too much about it.

**Comment by bartoszx** [comment]
Hi James

Thank you for your reply.

> The MOVED errors occur when you send a Key based command to a node that is not responsible for the corresponding hash slot. The error tells you which node to connect to instead. Actual Redis Cluster clients will manage these mappings and connections for you.
> 
This is correct. I’ve noticed that I had to setup rediscluster in php to solve this issue.
> Can you send me the steps to re-create the CLUSTERDOWN errors?... I remember getting that sometimes when setting up a new Redis Cluster with Swarm, considering it was transient and standing up a cluster is a one time kind of thing I didn't worry too much about it.
> 
Ahhh this is very random error. Even if it occur it is hard to recall whole steps :)
I will try to reproduce this again and I will let you know.

Bart

**Comment by jamespedwards42** [comment]
Closing this issue.

@bartoszx  Just to note.  If the cluster-announce-ip feature discussed in antirez/redis/issues/2527 supported hostnames as well as IP's it would make these scripts much less hacky and cluster discovery much cleaner because the Docker service names could be used directly for connecting.  Unfortunately, I think only one other person in that thread seems to have any interest in the idea.
